[build]
target = "x86_64-qywka_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]  # Сборка core для no_std
build-std-features = ["compiler-builtins-mem"] 

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
